path: './links'
urls:
  .: https://nickbair.net
  mrclr8r: https://lab.nickbair.net/marcellerator
  caleb: https://lab.nickbair.net/calebifier
  colored: https://f.njbai.rs/images/_/James%20Baron%20-%20Newspaper.jpg
  canadiantuxedo: https://www.isee.org/chapter-resources/chapter-speakers-bureau/477-mike-koehler
  github: https://github.com/njbair
